services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_DATABASE: 'workeverywhere'
      MYSQL_ROOT_PASSWORD: 'HaloPassword138'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'PastiPassword138'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    volumes:
      - app-db:/var/lib/mysql

  application:
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    container_name: work-everywhere-api
    env_file:
      - '.env.example'
    ports:
      - '127.0.0.1:8000:80'
    depends_on:
      database:
        condition: service_healthy


volumes:
  app-db:

networks:
  default:
    name: workeverywhere
